/***************************************************************************
 *     	signal.h - handles signals reported during a program's execution
 *
 *		This library supports ISO/IEC 9899:1990, 9899/AMD1:1995, and 9899:1999
 *
 *  Mon Apr  9 20:46:46 2007
 *  Copyright  2007  Gran Sasso, LLC
 *  Jeff DiClemente
 ****************************************************************************/

#ifndef _HCLIB_CONFIG_H
#define _HCLIB_CONFIG_H _HCLIB_CONFIG_H
#include <_HCLIB_config.h>
#endif
 
#ifndef _HCLIB_SIGNAL_H
#define _HCLIB_SIGNAL_H _HCLIB_SIGNAL_H


#define SIG_DFL	0	// signal default
#define SIG_ERR	1	// signal error
#define SIG_IGN	2	// signal ignore
#define SIGABRT	3	// abnormal termination (generated by the abort() function)
#define SIGFPE 	4	// floating point error (divide by 0, etc..)
#define SIGILL	5	// illegal operation
#define SIGINT 	6	// interactive attention signal (Ctrl-C)
#define SIGSEGV	7	// invalid access to storage (segment or memory violation)
#define SIGTERM 8	// termination request

/* TODO: use _HCLIB_XXXX macro in place of int? */
typedef int sig_atomic_t;

/* function declarations */

/*
 * sends signal, sig
 *
 *@param sig 	- one of the SIG* macros
 *@return int 	- zero on success
 *				- non-zero on failure
 */
int raise(int sig);

/*
 * controls how a signal is handled
 *
 *@param sig 		- one of the SIG* marcos
 *@param ptrfunc 	- pointer to handler function, OR
 *					- SIG_IDL (signal will be ignored), OR
 *					- SIG_DFL (default signal handler is used)
 *@return void
 */
void (* signal(int sig, void (*ptrfunc)(int)));

#endif 	// _HCLIB_SIGNAL_H
